services:
  - type: web
    name: product-recommendation-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: 3.10
